CREATE TABLE annual_aqi_by_county (
    State VARCHAR(255),
    County VARCHAR(255),
    Year INTEGER,
    "Days with AQI" INTEGER,
    "Good Days" INTEGER,
    "Moderate Days" INTEGER,
    "Unhealthy for Sensitive Groups Days" INTEGER,
    "Unhealthy Days" INTEGER,
    "Very Unhealthy Days" INTEGER,
    "Hazardous Days" INTEGER,
    "Max AQI" INTEGER,
    "90th Percentile AQI" INTEGER,
    "Median AQI" INTEGER,
    "Days CO" INTEGER,
    "Days NO2" INTEGER,
    "Days Ozone" INTEGER,
    "Days PM2.5" INTEGER,
    "Days PM10" INTEGER
);

CREATE TABLE annual_conc_by_monitor (
    "State Code" INTEGER,
    "County Code" INTEGER,
    "Site Num" INTEGER,
    "Parameter Code" INTEGER,
    "POC" INTEGER,
    "Latitude" NUMERIC,
    "Longitude" NUMERIC,
    "Datum" VARCHAR(50),
    "Parameter Name" VARCHAR(255),
    "Sample Duration" VARCHAR(255),
    "Pollutant Standard" VARCHAR(255),
    "Metric Used" VARCHAR(255),
    "Method Name" VARCHAR(255),
    "Year" INTEGER,
    "Units of Measure" VARCHAR(255),
    "Event Type" VARCHAR(50),
    "Observation Count" INTEGER,
    "Observation Percent" INTEGER,
    "Completeness Indicator" VARCHAR(10),
    "Valid Day Count" INTEGER,
    "Required Day Count" INTEGER,
    "Exceptional Data Count" INTEGER,
    "Null Data Count" INTEGER,
    "Primary Exceedance Count" INTEGER,
    "Secondary Exceedance Count" INTEGER,
    "Certification Indicator" VARCHAR(10),
    "Num Obs Below MDL" INTEGER,
    "Arithmetic Mean" NUMERIC,
    "Arithmetic Standard Dev" NUMERIC,
    "1st Max Value" NUMERIC,
    "1st Max DateTime" TIMESTAMP,
    "2nd Max Value" NUMERIC,
    "2nd Max DateTime" TIMESTAMP,
    "3rd Max Value" NUMERIC,
    "3rd Max DateTime" TIMESTAMP,
    "4th Max Value" NUMERIC,
    "4th Max DateTime" TIMESTAMP,
    "1st Max Non Overlapping Value" NUMERIC,
    "1st NO Max DateTime" TIMESTAMP,
    "2nd Max Non Overlapping Value" NUMERIC,
    "2nd NO Max DateTime" TIMESTAMP,
    "99th Percentile" NUMERIC,
    "98th Percentile" NUMERIC,
    "95th Percentile" NUMERIC,
    "90th Percentile" NUMERIC,
    "75th Percentile" NUMERIC,
    "50th Percentile" NUMERIC,
    "10th Percentile" NUMERIC,
    "Local Site Name" VARCHAR(255),
    "Address" VARCHAR(255),
    "State Name" VARCHAR(255),
    "County Name" VARCHAR(255),
    "City Name" VARCHAR(255),
    "CBSA Name" VARCHAR(255),
    "Date of Last Change" DATE
);

SELECT * FROM annual_aqi_by_county;
SELECT * FROM annual_conc_by_monitor;